ofxGui
ofxOsc
ofxPoco
./local_addons/ofxGeo
./local_addons/ofxHTTP
./local_addons/ofxIO
./local_addons/ofxMediaType
./local_addons/ofxNetworkUtils
./local_addons/ofxPd
./local_addons/ofxSSLManager
./local_addons/ofxTwitter
./local_addons/ofxXmlSettings
./local_addons/MSACore
./local_addons/MSAFluid
./local_addons/ofxAppUtils
./local_addons/ofxControlPanel
./local_addons/ofxFTGL
./local_addons/ofxNetwork
